### ISSUE TITLE
installation impossible

### ISSUE THREAD

**Issue by solaris13** [Simple-chez-tuxfamily/Simple-Music-Player#6]
bonjour, l'installation ne se fait pas j'ai une page blanche et dans apache error.log j'ai:
 PHP Fatal error:  Uncaught exception 'PDOException' with message 'could not find driver' in /var/www/html/Simple-Music-Player-master/installation/install.php:4\nStack trace:\n#0 /var/www/html/Simple-Music-Player-master/installation/install.php(4): PDO->__construct('sqlite:../core/...')\n#1 {main}\n  thrown in /var/www/html/Simple-Music-Player-master/installation/install.php on line 4, referer: http://192.168.0.11/Simple-Music-Player-master/installation/index.php

une idée?merci

**Comment by quent1-fr** [comment]
Bonjour,
« could not find driver » signifie que le driver sqlite 3 pour PHP n'est pas installé. 
Pour régler le souci, installez bon paquet (très cernainement php5-sqlite ou php-sqlite).
